#!/bin/bash

# color codes from dwm/config.h
color_grey="\x01" # grey on black
color_white="\x02" # white on black
color_darkgrey="\x04" # darkgrey on black
color_black="\x05" # black on darkgrey
color_red="\x06" # red on black
color_green="\x07" # green on black
color_orange="\x08" # orange on black
color_yellow="\x09" # yellow on black
color_blue="\x0A" # blue on darkgrey
color_magenta="\x0B" # magenta on darkgrey
color_cyan="\x0C" # cyan on darkgrey

# icon glyphs from xbmicons.bdf
glyph_mem="\uE010"
glyph_vol="\uE015"
glyph_light="\uE006"
glyph_time="\uE016"
glyph_wifi="\uE01E"
glyph_bat="\uE01F"
sep_solid="\uE01A"
sep_line="\uE01B"

print_mem_used() {
  mem_used="$(free -m | awk 'NR==2 {print $3}')"
  echo -ne "${color_yellow}${glyph_mem} ${mem_used}M "
}

print_wifi() {
  essid=$( /sbin/iwgetid -r ) 
  if [ -z "${essid}" ]
  then
    essid="---"
  fi
  echo -ne "${color_blue}${sep_line} ${glyph_wifi} ${essid} "
}

print_battery() {
  battery=$(( `cat /sys/class/power_supply/BAT0/energy_now` * 100 / `cat /sys/class/power_supply/BAT0/energy_full` ))
  battery_state=`cat /sys/class/power_supply/BAT0/status`
  echo -ne "${color_cyan}${sep_line} ${glyph_bat} ${battery}% ${battery_state} "
}

print_brightness() {
  brightness="$(printf "%.*f" 0 `xbacklight -get`)"
  echo -ne "${color_yellow}${sep_line} ${glyph_light} ${brightness}% "
}

print_volume() {
  state="$(amixer get Master | tail -n1 | sed -r 's/.*\[(.*)\]$/\1/')"
  if [ "$state" = "on" ]
  then
    volume="$(amixer get Master | tail -n1 | sed -r 's/.*\[(.*)%\].*/\1/')%"
  else
    volume="--"
  fi
  echo -ne "${color_magenta}${sep_line} ${glyph_vol} ${volume} "
}

print_datetime() {
  datetime="$(date "+%a %d %b ${sep_line} %I:%M %p")"
  echo -ne "${color_black}${sep_solid}${color_white}${glyph_time} ${datetime}"
}

while true; do
  xsetroot -name "$(print_mem_used)$(print_wifi)$(print_battery)$(print_brightness)$(print_volume)$(print_datetime)"
  sleep 0.5
done
