#!/bin/bash

# discover custom fonts
xset +fp ~/.local/share/fonts
xset fp rehash

# set background image
feh --bg-scale ~/Pictures/yosemite.jpg

# start background proceses
dwm-statusbar &
redshift &

# begin dwm session
dwm

# kill background processes
pkill redshift
pkill dwm-statusbar
exit
